version: "3"
services:
  go-template:
    build: .
    environment:
       RABBITMQ_URL: "amqp://rabbitmq"
    container_name: go-template
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.7.8-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./backend-data/rabbitmq:/var/lib/rabbitmq
    container_name: rabbitmq
